import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
export const escapeHtml = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const escapeVcard = s => s.replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(';','\\;').replaceAll(',','\\,');
export function vcard(p, photoBytes) {
 const lines=['BEGIN:VCARD','VERSION:3.0',`N:${escapeVcard(p.lastName)};${escapeVcard(p.firstName)};;;`,`FN:${escapeVcard(p.firstName+' '+p.lastName)}`,`ORG:${escapeVcard(p.company)}`,`TEL;TYPE=CELL:${p.phone}`,'END:VCARD'];
 if(p.title)lines.splice(-1,0,`TITLE:${escapeVcard(p.title)}`);
 if(p.email)lines.splice(-1,0,`EMAIL;TYPE=INTERNET,WORK:${p.email}`);
 if(p.website)lines.splice(-1,0,`URL:${escapeVcard(p.website)}`);
 if(p.address)lines.splice(-1,0,`ADR;TYPE=WORK:;;${['street','city','region','postalCode','country'].map(k=>escapeVcard(p.address[k]||'')).join(';')}`);
 if(photoBytes){const type=/\.jpe?g$/i.test(p.photo)?'JPEG':p.photo.split('.').pop().toUpperCase();lines.splice(-1,0,`PHOTO;ENCODING=b;TYPE=${type}:${photoBytes.toString('base64')}`);}
 return lines.map(line=>{let result='',bytes=0;for(const char of line){const n=Buffer.byteLength(char);if(bytes+n>75){result+='\r\n ';bytes=1;}result+=char;bytes+=n;}return result;}).join('\r\n')+'\r\n';
}
const icons={save:'<path d="M12 3v12m-5-5 5 5 5-5M5 17v4h14v-4"/>',call:'<path d="m7 3 3 5-3 3a15 15 0 0 0 6 6l3-3 5 3v3c0 1-1 2-2 2C10 21 3 14 2 5c0-1 1-2 2-2z"/>',text:'<path d="M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z"/><path d="M8 10h8m-8 4h5"/>',email:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]}</svg>`;
function page(p,base){const e=escapeHtml,name=e(p.firstName+' '+p.lastName);const address=p.address?['street','city','region','postalCode','country'].map(k=>p.address[k]).filter(Boolean).join(', '):'';const extra=(p.website?`<a href="${e(p.website)}"><span>WEBSITE</span><strong>${e(p.website.replace(/^https?:\/\//,'').replace(/\/$/,''))}</strong><b aria-hidden="true">↗</b></a>`:'')+(address?`<a href="https://www.google.com/maps/search/?api=1&amp;query=${encodeURIComponent(address)}"><span>OFFICE ADDRESS</span><strong>${e(p.address.street)}<br>${e([p.address.city,[p.address.region,p.address.postalCode].filter(Boolean).join(" ")].filter(Boolean).join(", "))}${p.address.country?"<br>"+e(p.address.country):""}</strong><b aria-hidden="true">↗</b></a>`:'');return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f2ee"><meta name="description" content="Connect with ${name} at ${e(p.company)}."><title>${name} | ${e(p.company)}</title><link rel="icon" href="${base}${e(p.logo||'logo.png')}"><link rel="stylesheet" href="${base}styles.css"></head>
<body style="--brand:${p.accent||'#c51b2e'};--brand-hover:${p.accentHover||'#aa1526'}"><main class="card"><header><img class="logo" src="${base}${e(p.logo||'logo.png')}" alt="${e(p.company)}" style="width:${p.logoWidth||118}px"></header>
<section class="identity" aria-labelledby="name"><div class="portrait-frame"><img class="portrait" src="${base}${e(p.webPhoto||p.photo)}" style="object-position:${e(p.photoPosition)};${p.photoScale?`transform:none;width:${p.photoScale*100}%;height:${p.photoScale*100}%;margin-left:${(1-p.photoScale)*50}%`:''}" alt="${name}" fetchpriority="high"></div><div class="intro"><p class="company">${e(p.company)}</p><h1 id="name">${name}</h1>${p.title?`<p class="title">${e(p.title).replace('/','<br>')}</p>`:''}</div></section>
<section class="connect" aria-label="Contact ${name}"><a class="save" href="${base}contacts/${p.slug}.vcf?v=photo-1" download="${p.slug}.vcf">${icon('save')}Save Contact<span class="arrow" aria-hidden="true">↗</span></a><div class="actions"><a href="tel:${p.phone}">${icon('call')}Call</a><a href="sms:${p.phone}">${icon('text')}Text</a>${p.email?`<a href="mailto:${e(p.email)}">${icon('email')}Email</a>`:''}</div>
<div class="details"><a href="tel:${p.phone}"><span>MOBILE</span><strong>${e(p.displayPhone)}</strong><b aria-hidden="true">↗</b></a>${p.email?`<a href="mailto:${e(p.email)}"><span>EMAIL</span><strong>${e(p.email)}</strong><b aria-hidden="true">↗</b></a>`:''}${extra}</div>
<details><summary>How to save this contact <span aria-hidden="true">+</span></summary><p>Tap <strong>Save Contact</strong> to open or download Jordan’s contact file. If it downloads, open the .vcf file from your downloads.</p><p><strong>iPhone:</strong> choose Create New Contact or Add to Existing Contact, then confirm.</p><p><strong>Android:</strong> open the file with Contacts, choose an account if asked, then save. Labels vary by phone.</p><p>Your phone will confirm when the contact is saved.</p></details></section></main></body></html>` .replace('Jordan’s contact file',`${e(p.firstName)}’s contact file`);}
export async function build(){const people=JSON.parse(await readFile('employees.json','utf8'));const slugs=new Set();for(const p of people){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)||slugs.has(p.slug))throw Error('Invalid or duplicate employee slug');slugs.add(p.slug);if(!/^\+[1-9]\d{7,14}$/.test(p.phone)||(p.email&&!/^[-\w.+]+@[\w.-]+\.[A-Za-z]{2,}$/.test(p.email)))throw Error('Invalid contact details');if(!/^[\w-]+\.(jpg|jpeg|png|webp)$/.test(p.photo)||!/^\d+% \d+%$/.test(p.photoPosition))throw Error('Invalid photo');}
for(const p of people){if(p.webPhoto&&!/^[\w-]+\.(jpg|jpeg|png|webp)$/.test(p.webPhoto))throw Error('Invalid web photo');if(p.logo&&!/^[\w-]+\.(png|jpg|jpeg|webp)$/.test(p.logo))throw Error('Invalid logo');if(p.logoWidth&&(!Number.isFinite(p.logoWidth)||p.logoWidth<60||p.logoWidth>200))throw Error('Invalid logo width');for(const color of [p.accent,p.accentHover])if(color&&!/^#[0-9a-f]{6}$/i.test(color))throw Error('Invalid brand color');if(p.photoScale&&(!Number.isFinite(p.photoScale)||p.photoScale<1||p.photoScale>2))throw Error('Invalid photo scale');if(p.website){const url=new URL(p.website);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Website must be an HTTP(S) URL without credentials');}if(p.address&&(!p.address.street||!p.address.city))throw Error('Office address requires street and city');}
if(!slugs.has('jordan-jones'))throw Error('Jordan must remain at the legacy root');
await mkdir('dist/contacts',{recursive:true});await copyFile('styles.css','dist/styles.css');await copyFile('logo.png','dist/logo.png');await writeFile('dist/.nojekyll','');for(const p of people){if(p.logo)await copyFile(p.logo,`dist/${p.logo}`);await copyFile(p.photo,`dist/${p.photo}`);if(p.webPhoto)await copyFile(p.webPhoto,`dist/${p.webPhoto}`);await mkdir(`dist/${p.slug}`,{recursive:true});await writeFile(`dist/${p.slug}/index.html`,page(p,'../'));await writeFile(`dist/contacts/${p.slug}.vcf`,vcard(p,await readFile(p.photo)));if(p.slug==='jordan-jones')await writeFile('dist/index.html',page(p,''));}console.log(`Built ${people.length} cards; legacy root preserved.`);}
if(process.argv[1]?.endsWith('build.mjs'))await build();
